export class AccountingEmployee {
    constructor(
        public id: number = 0,
        public User_Name: string = '',
        public en_name: string = '',
        public ar_name: string = '',
        public Password: string = '',
        public mobile: string = '',
        public phone: string = '',
        public email: string = '',
        public licenseNumber: string = '',
        public address: string = '',
        public nationalID: number = 0,
        public passportNumber: string = '',
        public residenceNumber: string = '',
        public birthdayDate: string = '',
        public nationality: number =0,
        public nationalityName: string = '',
        public expireDate: string = '',
        public dateOfAppointment: string = '',
        public dateOfLeavingWork: string = '',
        public monthSalary: number = 0,
        public hasAttendance: string = '',
        public attendanceTime: string = '',
        public departureTime: string = '',
        public delayAllowance: number = 0,
        public annualLeaveBalance: number = 0,
        public casualLeavesBalance: number = 0,
        public monthlyLeaveRequestBalance: number = 0,
        public graduationYear: number = 0,
        public note: string = '',
        public reasonOfLeavingID: number = 0,
        public reasonForLeavingWork: string = '',
        public departmentID: number = 0,
        public departmentName: string = '',
        public jobID: number = 0,
        public jobName: string = '',
        public academicDegreeID: number = 0,
        public academicDegreeName: string = '',
        public accountNumberName: string = '',
        public accountNumberID :number =0,
        public insertedByUserId :number =0,
        public insertedAt :number =0,
    ) {}
}
