// <auto-generated />
using System;
using LMS_CMS_DAL.Models.Domains;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS_CMS_DAL.Migrations.Domains
{
    [DbContext(typeof(LMS_CMS_Context))]
    [Migration("20241225134029_AcademicYearInClassroomMigration")]
    partial class AcademicYearInClassroomMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.BusModule.Bus", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<int>("BackPrice")
                        .HasColumnType("int");

                    b.Property<long?>("BusCompanyID")
                        .HasColumnType("bigint");

                    b.Property<long?>("BusDistrictID")
                        .HasColumnType("bigint");

                    b.Property<long?>("BusStatusID")
                        .HasColumnType("bigint");

                    b.Property<long?>("BusTypeID")
                        .HasColumnType("bigint");

                    b.Property<long>("Capacity")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DriverAssistantID")
                        .HasColumnType("bigint");

                    b.Property<long?>("DriverID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsertedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCapacityRestricted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MorningPrice")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TwoWaysPrice")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("BusCompanyID");

                    b.HasIndex("BusDistrictID");

                    b.HasIndex("BusStatusID");

                    b.HasIndex("BusTypeID");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("DriverAssistantID");

                    b.HasIndex("DriverID");

                    b.HasIndex("InsertedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Bus");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.BusModule.BusCategory", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsertedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("InsertedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("BusCategory");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.BusModule.BusCompany", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsertedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("InsertedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("BusCompany");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.BusModule.BusDistrict", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsertedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("InsertedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("BusDistrict");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.BusModule.BusStatus", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsertedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("InsertedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("BusStatus");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.BusModule.BusStudent", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("BusCategoryID")
                        .HasColumnType("bigint");

                    b.Property<long>("BusID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ExceptionFromDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionToDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsertedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsException")
                        .HasColumnType("bit");

                    b.Property<long>("SemseterID")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("BusCategoryID");

                    b.HasIndex("BusID");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("InsertedByUserId");

                    b.HasIndex("SemseterID");

                    b.HasIndex("StudentID");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("BusStudent");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.BusModule.BusType", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsertedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("InsertedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("BusType");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.Employee", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("BusCompanyID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("EmployeeTypeID")
                        .HasColumnType("bigint");

                    b.Property<string>("ExpireDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsertedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Role_ID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ar_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("en_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("BusCompanyID");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("EmployeeTypeID");

                    b.HasIndex("InsertedByUserId");

                    b.HasIndex("Role_ID");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("User_Name")
                        .IsUnique();

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.EmployeeAttachment", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("EmployeeID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsertedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("InsertedByUserId");

                    b.HasIndex("Link")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("EmployeeAttachment");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.EmployeeType", b =>
                {
                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("EmployeeType");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.AcademicYear", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("DateFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsertedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("SchoolID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("InsertedByUserId");

                    b.HasIndex("SchoolID");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("AcademicYear");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.Building", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsertedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("SchoolID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("InsertedByUserId");

                    b.HasIndex("SchoolID");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Building");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.Classroom", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("AcademicYearID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("FloorID")
                        .HasColumnType("bigint");

                    b.Property<long>("GradeID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsertedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("AcademicYearID");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("FloorID");

                    b.HasIndex("GradeID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("InsertedByUserId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Classroom");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.Floor", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FloorMonitorID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsertedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("buildingID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("FloorMonitorID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("InsertedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("buildingID");

                    b.ToTable("Floor");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.Grade", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsertedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("SectionID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("InsertedByUserId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SectionID");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Grade");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.School", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsertedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("SchoolTypeID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("InsertedByUserId");

                    b.HasIndex("SchoolTypeID");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("School");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.SchoolType", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsertedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("InsertedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("SchoolType");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.Section", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsertedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("SchoolID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("InsertedByUserId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SchoolID");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Section");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.Semester", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long?>("AcademicYearID")
                        .HasColumnType("bigint");

                    b.Property<string>("DateFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsertedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("AcademicYearID");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("InsertedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Semester");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.Student", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsertedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("Parent_Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ar_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("en_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("InsertedByUserId");

                    b.HasIndex("Parent_Id");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("User_Name")
                        .IsUnique();

                    b.ToTable("Student");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.StudentAcademicYear", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("ClassID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("GradeID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsertedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("SchoolID")
                        .HasColumnType("bigint");

                    b.Property<long>("SemesterID")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ClassID");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("GradeID");

                    b.HasIndex("InsertedByUserId");

                    b.HasIndex("SchoolID");

                    b.HasIndex("SemesterID");

                    b.HasIndex("StudentID");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("StudentAcademicYear");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.Subject", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<double>("CreditHours")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("GradeID")
                        .HasColumnType("bigint");

                    b.Property<bool>("HideFromGradeReport")
                        .HasColumnType("bit");

                    b.Property<string>("IconLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsertedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfSessionPerWeek")
                        .HasColumnType("int");

                    b.Property<int>("OrderInCertificate")
                        .HasColumnType("int");

                    b.Property<int>("PassByDegree")
                        .HasColumnType("int");

                    b.Property<long>("SubjectCategoryID")
                        .HasColumnType("bigint");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalMark")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ar_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("en_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("GradeID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("InsertedByUserId");

                    b.HasIndex("SubjectCategoryID");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("ar_name")
                        .IsUnique();

                    b.HasIndex("en_name")
                        .IsUnique();

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.SubjectCategory", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsertedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("InsertedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("SubjectCategory");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.Page", b =>
                {
                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDisplay")
                        .HasColumnType("bit");

                    b.Property<long?>("Page_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("ar_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("en_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("Page_ID");

                    b.HasIndex("ar_name")
                        .IsUnique();

                    b.HasIndex("en_name")
                        .IsUnique();

                    b.ToTable("Page");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.Parent", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsertedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ar_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("en_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("InsertedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("User_Name")
                        .IsUnique();

                    b.ToTable("Parent");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.Role", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsertedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("InsertedByUserId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.Role_Detailes", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<bool>("Allow_Delete")
                        .HasColumnType("bit");

                    b.Property<bool>("Allow_Delete_For_Others")
                        .HasColumnType("bit");

                    b.Property<bool>("Allow_Edit")
                        .HasColumnType("bit");

                    b.Property<bool>("Allow_Edit_For_Others")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsertedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("Page_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("Role_ID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedByOctaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("InsertedByUserId");

                    b.HasIndex("Page_ID");

                    b.HasIndex("Role_ID");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Role_Detailes");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.BusModule.Bus", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Domains.BusModule.BusCompany", "BusCompany")
                        .WithMany("Buses")
                        .HasForeignKey("BusCompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LMS_CMS_DAL.Models.Domains.BusModule.BusDistrict", "BusDistrict")
                        .WithMany("Buses")
                        .HasForeignKey("BusDistrictID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LMS_CMS_DAL.Models.Domains.BusModule.BusStatus", "BusStatus")
                        .WithMany("Buses")
                        .HasForeignKey("BusStatusID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LMS_CMS_DAL.Models.Domains.BusModule.BusType", "BusType")
                        .WithMany("Buses")
                        .HasForeignKey("BusTypeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "DeletedByEmployee")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "DriverAssistant")
                        .WithMany("DriverAssistant")
                        .HasForeignKey("DriverAssistantID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "Driver")
                        .WithMany("DrivenBuses")
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "InsertedByEmployee")
                        .WithMany()
                        .HasForeignKey("InsertedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("BusCompany");

                    b.Navigation("BusDistrict");

                    b.Navigation("BusStatus");

                    b.Navigation("BusType");

                    b.Navigation("DeletedByEmployee");

                    b.Navigation("Driver");

                    b.Navigation("DriverAssistant");

                    b.Navigation("InsertedByEmployee");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.BusModule.BusCategory", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "DeletedByEmployee")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "InsertedByEmployee")
                        .WithMany()
                        .HasForeignKey("InsertedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("DeletedByEmployee");

                    b.Navigation("InsertedByEmployee");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.BusModule.BusCompany", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "DeletedByEmployee")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "InsertedByEmployee")
                        .WithMany()
                        .HasForeignKey("InsertedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("DeletedByEmployee");

                    b.Navigation("InsertedByEmployee");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.BusModule.BusDistrict", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "DeletedByEmployee")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "InsertedByEmployee")
                        .WithMany()
                        .HasForeignKey("InsertedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("DeletedByEmployee");

                    b.Navigation("InsertedByEmployee");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.BusModule.BusStatus", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "DeletedByEmployee")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "InsertedByEmployee")
                        .WithMany()
                        .HasForeignKey("InsertedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("DeletedByEmployee");

                    b.Navigation("InsertedByEmployee");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.BusModule.BusStudent", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Domains.BusModule.BusCategory", "BusCategory")
                        .WithMany("BusStudents")
                        .HasForeignKey("BusCategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_CMS_DAL.Models.Domains.BusModule.Bus", "Bus")
                        .WithMany("BusStudents")
                        .HasForeignKey("BusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "DeletedByEmployee")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "InsertedByEmployee")
                        .WithMany()
                        .HasForeignKey("InsertedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.LMS.Semester", "Semester")
                        .WithMany("BusStudents")
                        .HasForeignKey("SemseterID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_CMS_DAL.Models.Domains.LMS.Student", "Student")
                        .WithMany("BusStudents")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("Bus");

                    b.Navigation("BusCategory");

                    b.Navigation("DeletedByEmployee");

                    b.Navigation("InsertedByEmployee");

                    b.Navigation("Semester");

                    b.Navigation("Student");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.BusModule.BusType", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "DeletedByEmployee")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "InsertedByEmployee")
                        .WithMany()
                        .HasForeignKey("InsertedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("DeletedByEmployee");

                    b.Navigation("InsertedByEmployee");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.Employee", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Domains.BusModule.BusCompany", "BusCompany")
                        .WithMany("Employees")
                        .HasForeignKey("BusCompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "DeletedByEmployee")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.EmployeeType", "EmployeeType")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "InsertedByEmployee")
                        .WithMany()
                        .HasForeignKey("InsertedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Role", "Role")
                        .WithMany("Employess")
                        .HasForeignKey("Role_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("BusCompany");

                    b.Navigation("DeletedByEmployee");

                    b.Navigation("EmployeeType");

                    b.Navigation("InsertedByEmployee");

                    b.Navigation("Role");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.EmployeeAttachment", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "DeletedByEmployee")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "Employee")
                        .WithMany("EmployeeAttachments")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "InsertedByEmployee")
                        .WithMany()
                        .HasForeignKey("InsertedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("DeletedByEmployee");

                    b.Navigation("Employee");

                    b.Navigation("InsertedByEmployee");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.AcademicYear", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "DeletedByEmployee")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "InsertedByEmployee")
                        .WithMany()
                        .HasForeignKey("InsertedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.LMS.School", "School")
                        .WithMany("AcademicYears")
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("DeletedByEmployee");

                    b.Navigation("InsertedByEmployee");

                    b.Navigation("School");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.Building", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "DeletedByEmployee")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "InsertedByEmployee")
                        .WithMany()
                        .HasForeignKey("InsertedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.LMS.School", "school")
                        .WithMany("Buildings")
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("DeletedByEmployee");

                    b.Navigation("InsertedByEmployee");

                    b.Navigation("UpdatedByEmployee");

                    b.Navigation("school");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.Classroom", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Domains.LMS.AcademicYear", "AcademicYear")
                        .WithMany("Classrooms")
                        .HasForeignKey("AcademicYearID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "DeletedByEmployee")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.LMS.Floor", "Floor")
                        .WithMany("Classrooms")
                        .HasForeignKey("FloorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_CMS_DAL.Models.Domains.LMS.Grade", "Grade")
                        .WithMany("Classrooms")
                        .HasForeignKey("GradeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "InsertedByEmployee")
                        .WithMany()
                        .HasForeignKey("InsertedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("AcademicYear");

                    b.Navigation("DeletedByEmployee");

                    b.Navigation("Floor");

                    b.Navigation("Grade");

                    b.Navigation("InsertedByEmployee");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.Floor", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "DeletedByEmployee")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "floorMonitor")
                        .WithMany("Floors")
                        .HasForeignKey("FloorMonitorID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "InsertedByEmployee")
                        .WithMany()
                        .HasForeignKey("InsertedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.LMS.Building", "building")
                        .WithMany("Floors")
                        .HasForeignKey("buildingID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeletedByEmployee");

                    b.Navigation("InsertedByEmployee");

                    b.Navigation("UpdatedByEmployee");

                    b.Navigation("building");

                    b.Navigation("floorMonitor");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.Grade", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "DeletedByEmployee")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "InsertedByEmployee")
                        .WithMany()
                        .HasForeignKey("InsertedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.LMS.Section", "Section")
                        .WithMany("Grades")
                        .HasForeignKey("SectionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("DeletedByEmployee");

                    b.Navigation("InsertedByEmployee");

                    b.Navigation("Section");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.School", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "DeletedByEmployee")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "InsertedByEmployee")
                        .WithMany()
                        .HasForeignKey("InsertedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.LMS.SchoolType", "SchoolType")
                        .WithMany("Schools")
                        .HasForeignKey("SchoolTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("DeletedByEmployee");

                    b.Navigation("InsertedByEmployee");

                    b.Navigation("SchoolType");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.SchoolType", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "DeletedByEmployee")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "InsertedByEmployee")
                        .WithMany()
                        .HasForeignKey("InsertedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("DeletedByEmployee");

                    b.Navigation("InsertedByEmployee");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.Section", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "DeletedByEmployee")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "InsertedByEmployee")
                        .WithMany()
                        .HasForeignKey("InsertedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.LMS.School", "school")
                        .WithMany("Sections")
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("DeletedByEmployee");

                    b.Navigation("InsertedByEmployee");

                    b.Navigation("UpdatedByEmployee");

                    b.Navigation("school");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.Semester", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Domains.LMS.AcademicYear", "AcademicYear")
                        .WithMany("Semesters")
                        .HasForeignKey("AcademicYearID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "DeletedByEmployee")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "InsertedByEmployee")
                        .WithMany()
                        .HasForeignKey("InsertedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("AcademicYear");

                    b.Navigation("DeletedByEmployee");

                    b.Navigation("InsertedByEmployee");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.Student", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "DeletedByEmployee")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "InsertedByEmployee")
                        .WithMany()
                        .HasForeignKey("InsertedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Parent", "Parent")
                        .WithMany("Students")
                        .HasForeignKey("Parent_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("DeletedByEmployee");

                    b.Navigation("InsertedByEmployee");

                    b.Navigation("Parent");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.StudentAcademicYear", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Domains.LMS.Classroom", "Classroom")
                        .WithMany("StudentAcademicYears")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "DeletedByEmployee")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.LMS.Grade", "Grade")
                        .WithMany("StudentAcademicYears")
                        .HasForeignKey("GradeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "InsertedByEmployee")
                        .WithMany()
                        .HasForeignKey("InsertedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.LMS.School", "School")
                        .WithMany("StudentAcademicYears")
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_CMS_DAL.Models.Domains.LMS.Semester", "Semester")
                        .WithMany("StudentAcademicYears")
                        .HasForeignKey("SemesterID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_CMS_DAL.Models.Domains.LMS.Student", "Student")
                        .WithMany("StudentAcademicYears")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("Classroom");

                    b.Navigation("DeletedByEmployee");

                    b.Navigation("Grade");

                    b.Navigation("InsertedByEmployee");

                    b.Navigation("School");

                    b.Navigation("Semester");

                    b.Navigation("Student");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.Subject", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "DeletedByEmployee")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.LMS.Grade", "Grade")
                        .WithMany("Subjects")
                        .HasForeignKey("GradeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "InsertedByEmployee")
                        .WithMany()
                        .HasForeignKey("InsertedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.LMS.SubjectCategory", "SubjectCategory")
                        .WithMany("Subjects")
                        .HasForeignKey("SubjectCategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("DeletedByEmployee");

                    b.Navigation("Grade");

                    b.Navigation("InsertedByEmployee");

                    b.Navigation("SubjectCategory");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.SubjectCategory", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "DeletedByEmployee")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "InsertedByEmployee")
                        .WithMany()
                        .HasForeignKey("InsertedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("DeletedByEmployee");

                    b.Navigation("InsertedByEmployee");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.Page", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Domains.Page", "Parent")
                        .WithMany("ChildPages")
                        .HasForeignKey("Page_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.Parent", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "DeletedByEmployee")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "InsertedByEmployee")
                        .WithMany()
                        .HasForeignKey("InsertedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("DeletedByEmployee");

                    b.Navigation("InsertedByEmployee");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.Role", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "DeletedByEmployee")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "InsertedByEmployee")
                        .WithMany()
                        .HasForeignKey("InsertedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("DeletedByEmployee");

                    b.Navigation("InsertedByEmployee");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.Role_Detailes", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "DeletedByEmployee")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "InsertedByEmployee")
                        .WithMany()
                        .HasForeignKey("InsertedByUserId");

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Page", "Page")
                        .WithMany("Role_Detailes")
                        .HasForeignKey("Page_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Role", "Role")
                        .WithMany("Role_Detailes")
                        .HasForeignKey("Role_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_CMS_DAL.Models.Domains.Employee", "UpdatedByEmployee")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("DeletedByEmployee");

                    b.Navigation("InsertedByEmployee");

                    b.Navigation("Page");

                    b.Navigation("Role");

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.BusModule.Bus", b =>
                {
                    b.Navigation("BusStudents");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.BusModule.BusCategory", b =>
                {
                    b.Navigation("BusStudents");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.BusModule.BusCompany", b =>
                {
                    b.Navigation("Buses");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.BusModule.BusDistrict", b =>
                {
                    b.Navigation("Buses");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.BusModule.BusStatus", b =>
                {
                    b.Navigation("Buses");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.BusModule.BusType", b =>
                {
                    b.Navigation("Buses");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.Employee", b =>
                {
                    b.Navigation("DrivenBuses");

                    b.Navigation("DriverAssistant");

                    b.Navigation("EmployeeAttachments");

                    b.Navigation("Floors");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.EmployeeType", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.AcademicYear", b =>
                {
                    b.Navigation("Classrooms");

                    b.Navigation("Semesters");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.Building", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.Classroom", b =>
                {
                    b.Navigation("StudentAcademicYears");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.Floor", b =>
                {
                    b.Navigation("Classrooms");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.Grade", b =>
                {
                    b.Navigation("Classrooms");

                    b.Navigation("StudentAcademicYears");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.School", b =>
                {
                    b.Navigation("AcademicYears");

                    b.Navigation("Buildings");

                    b.Navigation("Sections");

                    b.Navigation("StudentAcademicYears");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.SchoolType", b =>
                {
                    b.Navigation("Schools");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.Section", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.Semester", b =>
                {
                    b.Navigation("BusStudents");

                    b.Navigation("StudentAcademicYears");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.Student", b =>
                {
                    b.Navigation("BusStudents");

                    b.Navigation("StudentAcademicYears");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.LMS.SubjectCategory", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.Page", b =>
                {
                    b.Navigation("ChildPages");

                    b.Navigation("Role_Detailes");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.Parent", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Domains.Role", b =>
                {
                    b.Navigation("Employess");

                    b.Navigation("Role_Detailes");
                });
#pragma warning restore 612, 618
        }
    }
}
