export class ShopItem {
    constructor(
        public id: number = 0,
        public enName: string = '',
        public arName: string = '',
        public enDescription: string = '',
        public arDescription: string = '',
        public purchasePrice: number =0,
        public salesPrice: number =0,
        public vatForForeign: number =0,
        public genderId: number =0,
        public genderName: string = '',
        public limit: number =0,
        public availableInShop: boolean =false,
        public mainImageFile:  File|null = null,
        public otherImageFile: File|null = null,
        public mainImage:  string = '',
        public otherImage: string = '',
        public inventorySubCategoriesID: number =0,
        public inventorySubCategoriesName: string = '',
        public schoolName: string = '',
        public schoolID: number =0, 
        public gradeName: string = '',
        public gradeID: number =0,
        public insertedByUserId :number =0,
        public insertedAt :string ="",
        public shopItemColors :any = "",
        public shopItemSizes :any ="",
    ) {}
}         