export class ShopItem {
    constructor(
        public id: number = 0,
        public enName: string = '',
        public arName: string = '',
        public enDescription: string = '',
        public arDescription: string = '',
        public purchasePrice: number|null = null,
        public salesPrice: number = 0,
        public vatForForeign: number|null = null,
        public genderID: number =0,
        public genderName: string = '',
        public limit: number|null = null,
        public availableInShop: boolean =false,
        public mainImageFile:  File|null = null,
        public otherImageFile: File|null = null,
        public mainImage:  string = '',
        public otherImage: string = '',
        public inventoryCategoriesID: number = 0,
        public inventorySubCategoriesID: number = 0,
        public inventorySubCategoriesName: string = '',
        public schoolName: string = '',
        public schoolID: number =0, 
        public gradeName: string = '',
        public gradeID: number =0,
        public insertedByUserId :number =0,
        public insertedAt :string ="",
        public shopItemColors :any[] = [],
        public shopItemSizes :any[] = [],
        public barCode :string ="",
    ) {}
}         