// <auto-generated />
using LMS_CMS_DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS_CMS_DAL.Migrations
{
    [DbContext(typeof(LMS_CMS_Context))]
    partial class LMS_CMS_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMS_CMS_DAL.Models.Detailed_Permissions", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Master_Permission_ID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("Master_Permission_ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Detailed_Permissions");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("User_Name")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Master_Permissions", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Master_Permissions");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Parent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("User_Name")
                        .IsUnique();

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Role_Detailed_Permissions", b =>
                {
                    b.Property<int>("Role_ID")
                        .HasColumnType("int");

                    b.Property<int>("Detailed_Permissions_ID")
                        .HasColumnType("int");

                    b.HasKey("Role_ID", "Detailed_Permissions_ID");

                    b.HasIndex("Detailed_Permissions_ID");

                    b.ToTable("Role_Detailed_Permissions");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Parent_Id")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("Parent_Id");

                    b.HasIndex("User_Name")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Detailed_Permissions", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Master_Permissions", "Master_Permissions")
                        .WithMany("Detailed_Permissions")
                        .HasForeignKey("Master_Permission_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master_Permissions");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Role_Detailed_Permissions", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Detailed_Permissions", "Detailed_Permissions")
                        .WithMany("Role_Detailed_Permissions")
                        .HasForeignKey("Detailed_Permissions_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS_CMS_DAL.Models.Role", "Role")
                        .WithMany("Role_Detailed_Permissions")
                        .HasForeignKey("Role_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detailed_Permissions");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Student", b =>
                {
                    b.HasOne("LMS_CMS_DAL.Models.Parent", "Parent")
                        .WithMany("Students")
                        .HasForeignKey("Parent_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Detailed_Permissions", b =>
                {
                    b.Navigation("Role_Detailed_Permissions");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Master_Permissions", b =>
                {
                    b.Navigation("Detailed_Permissions");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Parent", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("LMS_CMS_DAL.Models.Role", b =>
                {
                    b.Navigation("Role_Detailed_Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
